linters:
  disable-all: true
  enable:
    - errcheck
    - ineffassign
    - unconvert
    - misspell
    - gofumpt
    - govet
    - unused
    - goconst
    - gosec
    - staticcheck
issues:
  exclude:
    - composite
run:
  tests: false
